apps/projects/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('projects.views',
                       # (r'^()/$', 'callback', {}, 'pubsubhubbub_callback'),
                       (r'^(?P<project_id>\d+)/$', 'project_view', {}, 'project_view'),
                       (r'^$', 'project_list', {}, 'project_list'),
                       (r'^new/$', 'new_project', {}, 'new_project'),
                       (r'^json/$', 'json_project_activities', {}, 'json_project_activities'),
                       )

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.shortcuts import redirect

from django.contrib import admin
admin.autodiscover()

from pinax.apps.account.openid_consumer import PinaxConsumer



handler500 = "pinax.views.server_error"


if settings.ACCOUNT_OPEN_SIGNUP:
    signup_view = "pinax.apps.account.views.signup"
else:
    signup_view = "pinax.apps.signup_codes.views.signup"

def home_view(request):
    if request.user.is_authenticated():
        return redirect('/projects/')
    else:
        return redirect('/account/login/')

urlpatterns = patterns("",
    url(r"^$", home_view, name="home"),
    
    url(r"^admin/invite_user/$", "pinax.apps.signup_codes.views.admin_invite_user", name="admin_invite_user"),
    url(r"^account/signup/$", signup_view, name="acct_signup"),
    
    (r"^about/", include("about.urls")),
    (r"^account/", include("pinax.apps.account.urls")),
    (r"^openid/(.*)", PinaxConsumer()),
    (r"^profiles/", include("basic_profiles.urls")),
    (r"^notices/", include("notification.urls")),
    (r"^announcements/", include("announcements.urls")),    
    
    (r"^admin/", include(admin.site.urls)),
    
    # (r"^pshb/", include("djpubsubhubbub.urls")),
    
    (r"^projects/", include("projects.urls")),
    (r"^activity/", include("activity.urls")),
    
)


if settings.SERVE_MEDIA:
    urlpatterns += patterns("",
        (r"", include("staticfiles.urls")),
    )

apps/activity/models.py
from django.db import models
from taggit.managers import TaggableManager
import datetime
import dateutil.parser
import dateutil.tz

# from djpubsubhubbub import signals
from django.contrib.auth.models import User



class Activity(models.Model):
    """(Modelname description)"""
    title = models.TextField(blank=True)
    subtitle = models.TextField(blank=True)
    type = models.TextField(blank=True)
    url = models.TextField(blank=True)
    username = models.TextField(blank=True)
    user = models.ForeignKey(User)
    source = models.TextField(blank=True)
    created = models.DateTimeField(blank=True, default=datetime.datetime.now)
    
    tags = TaggableManager()
    
    def save(self, *args, **kwargs):
        ea_model = models.get_model('external_applications', 'ExternalApplication')
        ea = ea_model.objects.filter(application=self.source, username__iexact=self.username)
        if ea:
            self.user = ea[0].user
            
        super(Activity, self).save(*args, **kwargs)

            

    class Meta:
        verbose_name_plural = "Activities"
        
    def __unicode__(self):
        return "(%s) - %s" % (self.title, self.subtitle)
        
        
class ActivityComment(models.Model):
    belongs_to = models.ForeignKey(Activity)
    author = models.ForeignKey(User)
    comment = models.TextField(blank=False)
    pub_date = models.DateTimeField(blank=True, default=datetime.datetime.now)
    
    class Meta:
        get_latest_by = "pub_date"
    
    def __unicode__(self):
        return "%s - %s" % (self.author, self.comment)
    
    
        
def parse_activitystream(sender, **kwargs):
    """docstring for print_it"""
    
    def parse_date(s):
        """
        Convert a string into a (local, naive) datetime object.
        """
        dt = dateutil.parser.parse(s)
        if dt.tzinfo:
            dt = dt.astimezone(dateutil.tz.tzlocal()).replace(tzinfo=None)
        return dt
    
    print "received something"
    print kwargs['update']
        
    title = kwargs['update']['entries'][0]['title']
    created = parse_date(kwargs['update']['entries'][0]['published'])
    
    subtitle = ""
    
    try:
        summary = kwargs['update']['entries'][0]['summary_detail']['value']
    except:
        summary = ""
        
    try:
        subtitle = kwargs['update']['entries'][0]['subtitle']
    except:
        subtitle = ""
        
    url = kwargs['update']['entries'][0]['links'][0]['href']
    username = kwargs['update']['entries'][0]['author_detail']['name']
    
    for tag in kwargs['update']['entries'][0]['tags']:
        if tag['scheme'] == "http://schemas.cliqset.com/activity/categories/1.0":
            act_type = tag['label']      

    act = Activity.objects.create(
        title = title,
        subtitle = subtitle or summary,
        url = url,
        username = username,
        type = act_type,
        created = created
    )
    
    for tag in kwargs['update']['entries'][0]['tags']:
        if tag['scheme'] == "http://schemas.cliqset.com/activity/tags/1.0":
            act.tags.add(tag['label'])
            
    [Ac.tags.add(tag) for tag in ['fds', 'dferf', 'fd2rfw']]
    

# signals.updated.connect(parse_activitystream)

apps/projects/models.py
from django.db import models
from taggit.managers import TaggableManager
import datetime
from django.utils.translation import ugettext_lazy as _


class Project(models.Model):
    """(Modelname description)"""
    title = models.CharField(_("name"), max_length=150, blank=True, help_text="Something short and snappy works best")
    description = models.TextField(_("description"), blank=True, help_text="A sentence or two about your project")
    created = models.DateTimeField(blank=True, default=datetime.datetime.now)
    
    tags = TaggableManager()
    
    def __unicode__(self):
        return self.title
    
    def items(self, after_timestamp = 0):
        """
        Returns Queryset containing all items that are:
                (a) associated with a project and approved
                (b) tagged with a projects tag and approved
        """

        activity_model = models.get_model('activity', 'Activity')
        project_tags = self.tags.all()
        
        project_tag_list = []
        
        for tag in project_tags.values():
            project_tag_list.append(tag['name'].lower())
                    
        if after_timestamp == 0:
            return activity_model.objects.filter(tags__name__in=project_tag_list).order_by('-created').distinct()
        else:
            after_datetime = datetime.datetime.fromtimestamp(after_timestamp+1)
            return activity_model.objects.filter(tags__name__in=project_tag_list, created__gt=after_datetime).order_by('-created').distinct()
        

apps/projects/forms.py
from django import forms
from django.conf import settings

from projects.models import Project



class NewProjectForm(forms.ModelForm):
    # tags = forms.CharField(max_length=255, help_text="Press enter after each tag to add it")
    
    class Meta:
        model = Project
        exclude = ("created",)

apps/projects/views.py
from django.shortcuts import render_to_response, get_object_or_404
from projects.models import Project
from projects.forms import NewProjectForm
from themes.models import Theme

from django.contrib.auth.models import User

from django.template import RequestContext
import time
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.utils import simplejson


@login_required
def project_view(request, project_id, template_name="projects/project.html"):
    
    project = get_object_or_404(Project, id=project_id)
    # theme = Theme.objects.get(active=True)
    
    items = project.items()
    # last_updated_stamp = str(int(time.mktime(items[0].created.timetuple())))
    
    user_objects = []
    users = project.items().values("user")
    user_list = set(v for d in users for k,v in d.items())
    for user_id in user_list:
        user_objects.append(User.objects.get(pk=user_id))
    
    
    
    try:
        delicious_username = request.user.externalapplication_set.get(application='delicious').username
    except:
        delicious_username = ""
    
    
    return render_to_response(template_name, {
        # "theme": theme,
        "project": project,
        "items": items,
        "delicious_username": delicious_username,
        "users": user_objects
    }, context_instance=RequestContext(request))
    

@login_required
def project_list(request, template_name="projects/project_list.html"):

    projects = Project.objects.all()


    return render_to_response(template_name, {
        "projects": projects,
    }, context_instance=RequestContext(request))
    
def json_project_activities(request):
    """docstring for json_project_activities"""
    
    timestamp = int(request.GET['dt'])
    pid = int(request.GET['id'])
    
    project = get_object_or_404(Project, id=pid)
    
    
    items = project.items(timestamp)
    
    objs = []
    for item in items:        
        # p.items()[0].tags.all().values()
        
        objs.append({
            "username": item.username,
            "tags": [tag['name'] for tag in item.tags.values()],
            "type": item.type,
            "source": item.source,
            "title":item.title,
            "subtitle": item.subtitle,
            "dt": "just now",
        })
        
    return HttpResponse(simplejson.dumps(objs), mimetype='application/javascript')
    
@login_required
def new_project(request, form_class=NewProjectForm, **kwargs):

    template_name = kwargs.get("template_name", "projects/project_new.html")

    if request.method == "POST":
        project_form = form_class(request.POST)
        if project_form.is_valid():
            project = project_form.save()
            return HttpResponseRedirect(reverse("project_view", args=[project.id]))
    else:
        project_form = form_class()

    return render_to_response(template_name, {
        "project_form": project_form,
    }, context_instance=RequestContext(request))
    

templates/projects/project.html
{% extends "base.html" %}

{% load i18n %}
{% load uni_form_tags %}
{% load ifsetting_tag %}
{% load account_tags %}

{% block head_title %}{% trans "Super Secret Project Management App" %}{% endblock %}

{% block extra_head %}
<script src="{{ STATIC_URL }}js/mustache.js"></script>
<script src="{{ STATIC_URL }}js/tsort.js"></script>
{% endblock %}

{% block body %}
	
	<h1>{{project.title}} {# <a href="#" class="yum-button edit-project"><span>Edit Project</span></a> #}</h1>
	<div id="project-description">{{project.description}}</div>
	
	<div id="filter-bar">
		<h3>Filter Bar</h3>
	</div>
	<div id="filter-container">
		<div id="filter-sort-control">
			<h4>Sort</h4>
			<a href="#" class="filter-button selected" id="filter-newest"><span>Newest First</span></a>
			<a href="#" class="filter-button" id="filter-oldest"><span>Oldest First</span></a>
			<a href="#" class="filter-button" id="filter-active"><span>Recently Active</span></a>
		</div>
		<div id="filter-tags-control" class="filter-options-container">
			<h4>Tags {# <a href="#">Manage Tags</a> #}</h4>
			<a href="#" class="filter-button all selected"><span>All</span></a>
			{% for tag in project.tags.all %}
				<a href="#" class="filter-button" id="filter-tag-{{tag|lower}}"><span><strong>{{tag}}</strong></span></a>
			{% endfor %}
		</div>
		<div id="filter-users-control" class="filter-options-container">
			<h4>Users {# <a href="#">Manage Users</a> #}</h4>
			<a href="#" class="filter-button all selected"><span>All</span></a>
			{% for user in users %}
			  <a href="#" class="filter-button" id="filter-user-{{user}}"><span>{{user}}</span></a>
			{% endfor %}
		</div>
		<div id="filter-type-control" class="filter-options-container">
			<h4>Type {# <a href="#">Manage Apps</a> #}</h4>
			<a href="#" class="filter-button all selected"><span>All</span></a>
			<a href="#" class="filter-button" id="filter-type-note"><span>Note</span></a>
			<a href="#" class="filter-button" id="filter-type-email"><span>Email</span></a>
			<a href="#" class="filter-button" id="filter-type-bookmark"><span>Bookmark</span></a>
			<a href="#" class="filter-button" id="filter-type-activity"><span>Activity</span></a>
			<a href="#" class="filter-button" id="filter-type-citation"><span>Citation</span></a>
			<a href="#" class="filter-button" id="filter-type-workflow"><span>Workflow</span></a>
		</div>
	</div>
	<div href="#" id="updates-container"></div>
	<div id="activity-stream">
		
		{% for item in items %}
			<div class="activity meta-user-{{item.user}} meta-type-{{item.type}} {% for tag in item.tags.all %}meta-tag-{{tag|lower}} {% endfor %}">
		        <span class="activity-source"><span><img src="{{ STATIC_URL }}images/icons/{{item.source}}-24x24.png" alt="">{{item.type|capfirst}}</span></span>
		        <a href="{% firstof item.url "#" %}" class="activity-title" title="{{item.title}}">{{item.title|truncatewords:3}}</a>
		        <span class="activity-meta">— {{item.type|capfirst}} by {{item.user}}, <em id="timestamp-{{ item.created|date:"U" }}">{{ item.created|timesince }}</em> ago.</span>
		        <a href="#" class="yum-button comment"><span id="activity-timestamp-{% firstof item.activitycomment_set.latest.pub_date|date:"U" item.created|date:"U" %}">{{item.activitycomment_set.all.count}} Comments</span></a>
		        <a href="#" class="actions"></a>
		        
		        <div class="comments-container">
                    <ol class="comment-list">
                        {% for comment in item.activitycomment_set.all %}
                        <li class="comment-body">
                            <div class="comment-meta">
                                <div class="comment-time">{{ comment.pub_date|timesince }}</div>
                                <div class="comment-author"><em>{{ comment.author }}</em> said:</div>
                            </div>
                            
                            <p>{{comment.comment}}</p>
                        </li>
                        {% endfor %}
                    </ol>
                    <div class="make-coment">
                        <form method="POST" action="{% url make_comment %}" class="comment-box">
                            {% csrf_token %}
                            <input type="hidden" name="activity_id" value="{{item.id}}">
                            <input type="submit" style="float:right; margin-top:80px; padding:5px" class="comment-submit" value="Save Comment"> 
                            <textarea id="" cols="70" rows="5"name="comment" style="float:right; margin:10px; padding:5px"></textarea> 
                        </form>
                        
                        <div style="clear:both"></div> 
                    </div>
		        </div>

		    </div>
	    {% empty %}
            <p class="activitystream_info">This project's activity stream is empty! To add content simply tag something using one of these tags: <em>{% for tag in project.tags.all %}{{tag}}{% if forloop.last %}{% else %}, {% endif %}{% endfor %}</em>.</p>
        {% endfor %}

   	</div>		
	
{% endblock body %}

{% block extra_body %}
<script type="text/javascript">

update_stamp = {% firstof items.0.created|date:"U" "0" %};


(function($) {
    $.poll = function(options){
        var $this = $(this);

        var opts = $.extend({}, $.poll.defaults, options);
        setInterval(update, opts.interval);

        function update(){
            $.ajax({
                type: opts.type,
                url: opts.url,
                dataType: opts.dataType,
                success: opts.success
            });
        };
    };

    $.poll.defaults = {
        type: "POST",
        url: ".",
        success: '',
        interval: 2000,
        dataType: "json"
    };
})(jQuery);

$("#filter-newest").click(function(){
    $("div.activity").tsort(".activity-meta>em", {attr:"id", order:"desc"});
})
$("#filter-oldest").click(function(){
    $("div.activity").tsort(".activity-meta>em", {attr:"id", order:"asc"});
})
$("#filter-active").click(function(){
    $("div.activity").tsort(".comment>span", {attr:"id", order:"desc"});
})

function updateDelicious (data) {
	console.log("1: "+data)
	if ( parseInt(data) > 0) {
		$.getJSON('/projects/json/?dt='+update_stamp+'&id='+{{project.id}}, function(data) {
		    update_stamp = Math.round(new Date().getTime() / 1000)
            console.log("2: "+data)
			console.log("len(2): "+data.length)
            activity_view = {
            "items": data,
            "capitalise": function() {
              return function(text, render) {
                  return render(text).substr(0, 1).toUpperCase() + render(text).substr(1);
              }
            }}

			if (parseInt(data.length) > 0) {
                $("#updates-container").addClass("new-activities");
                $("#updates-container").html("<strong><em>"+data.length+"</em> new activities.</strong> (Click here to view them on activity stream)")
        	}
        });
	}
}

previous_updates = 0;


$(document).ready(function(){
	
	// This code is for demo purposes, it will be moved into the activity stream scraper at some point.
	
	$.getJSON('/activity/update_delicious/?username={{delicious_username}}', updateDelicious);

	$.ajax({
	    url: "http://feeds.delicious.com/v2/json/{{delicious_username}}",
	    type: "GET",
	    dataType: "jsonp",
	    success: function(data){
	     console.log(data);
	     initial_data = data;
	    }
	});


});

$.poll({
    url: "http://feeds.delicious.com/v2/json/{{delicious_username}}",
    interval: 30000,
    type: "GET",
    dataType: "jsonp",
    success: function(data){
        var updates = updatesToJSONFeed(initial_data, data);
        console.log(updates);

        if (updates > previous_updates) {
            $.getJSON('/activity/update_delicious/?username={{delicious_username}}', updateDelicious);
        }
        previous_updates = updates
    }
});

        $("form.comment-box").submit(function(){
            c_container = this;
            if ($(this).children("textarea").val() != "") {
                $.post($(this).attr("action"), $(this).serialize(), function (data) {
                    console.log("D: "+data)
                    // if (data == true) {
                        console.log("in");
                        var text = $(c_container).children("textarea").val();
                        console.log(text);
        
        
                        var comment_list = $(c_container).parent().parent().children(".comment-list");
                        console.log(comment_list);
                        var comment = comment_list.append(
                            "<li class='comment-body'><div class='comment-meta'><div class='comment-time'>Just now</div><div class='comment-author'><em>{{request.user}}</em> said:</div></div><p>"+text+"</p></li>"
                        );

						var comment_notification = $(c_container).parent().parent().parent().children("a.comment");
						var num_comments = parseInt(comment_notification.text().slice(0, -9));
						num_comments = num_comments + 1;

						var comment_time = Math.round(new Date().getTime() / 1000)
						comment_notification.html('<span id="activity-timestamp-'+comment_time+'">'+num_comments+' Comments</span>');
        
                        comment.slideDown();
        
                        $(c_container).children("textarea").val("");
                    // }
                });
            }
            return false;
        });
        



	    // var updates = 1;
	    // if (updates) {
	    //      $("#updates-container").addClass("new-activities");
	    //      $("#updates-container").html("<strong><em>"+updates+"</em> new activities.</strong> (Click here to view them on the activity stream)")
	    //  }

        $(".new-activities").live("click", function(){
            $(".activitystream_info").hide();
			$('#activity-stream').prepend(Mustache.to_html(activity_template, activity_view));
			$("#updates-container").removeClass("new-activities");
        })

</script>

{% endblock extra_body %}

templates/projects/project_form.html
<form method="POST" action="{% url new_project %}" id="new-project-form">
    {% csrf_token %}
{% for field in project_form %}
<div class="form-item">
    <label for="">
        {{ field.label }}: <span>{{ field.help_text }}</span>
    </label>
    {{ field }}
</div>
{% endfor %}
<div class="form-buttons">
    <a href="{% url project_list %}" class="back-link">« Cancel</a>
    <a href="#" class="yum-button create-project"><span>Create New Project</span></a>
</div>
</form>

templates/projects/project_list.html
{% extends "base.html" %}

{% load i18n %}
{% load uni_form_tags %}
{% load ifsetting_tag %}
{% load account_tags %}

{% block head_title %}{% trans "Your Projects" %}{% endblock %}

{% block extra_head %}
{% endblock %}

{% block body %}
	
	<h1 class="no-seperator">Your Projects <a href="{% url new_project %}" class="yum-button new-project"><span>Create a New Project</span></a></h1>
	
	{% for project in projects %}
	<a href="{% url project_view project.id %}" class="project-list-item"> 
        {{project.title}}<span>{{project.description}}</span>
    </a>
    {% endfor %}
		
        {# {% for item in items %} #}
        {#  <div class="activity meta-user-{{item.username}} meta-type-{{item.type}} {% for tag in item.tags.all %}meta-tag-{{tag}} {% endfor %} meta-timestamp-{{ item.created|date:"U" }}"> #}
        {#         <span class="activity-source"><span><img src="{{ STATIC_URL }}images/icons/{{item.source}}-24x24.png" alt="">{{item.type|capfirst}}</span></span> #}
        {#         <a href="{% firstof item.url "#" %}" class="activity-title" title="{{item.title}}">{{item.title|truncatewords:3}}</a> #}
        {#         <span class="activity-meta">— {{item.type|capfirst}} by {{item.username}}, {{ item.created|timesince }} ago.</span> #}
        {#  #}
        {#         <a href="#" class="yum-button comment"><span>0 Comments</span></a> #}
        {#         <a href="#" class="actions"></a> #}
        {#     </div> #}
        {# {% endfor %} #}

	
{% endblock body %}

{% block extra_body %}


{% endblock extra_body %}

templates/projects/project_new.html
{% extends "base.html" %}
{% load i18n %}

{% block head_title %}{% blocktrans %}Create a New Project{% endblocktrans %}{% endblock %}

{% block extra_head %}
<script type="text/javascript" src="{{ STATIC_URL }}js/jquery.tag.editor-min.js"></script>
{% endblock %}

{% block body %}
    
    <h1 class="no-seperator">{% trans "Create a New Project" %}</h1> 
    
    {% include "projects/project_form.html" %}
    
    <script type="text/javascript">
	    $(function() {
	        $("#id_tags").tagEditor({
	                confirmRemoval: false,
					separator:",",
					completeOnSeparator: false
	        });
        })
        
        $(".create-project").click(function(){
            $("#new-project-form").submit();
        })
    </script>
    
{% endblock %}